var Nombre = "Jos";
var Apellido = "Muñoz";
var Musica = "Love me";
Musica += " Lil";
var Movie = "Twilight";
var J = 26;
var J = 29;
J = 2629;
console.log(Nombre);
console.log(Apellido);
console.log(Musica);
console.log(Movie);
console.log(J);
